"use strict";
const pageProgress=document.querySelector('#pageProgress');
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;pageProgress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});
const menu=document.querySelector('.menu-button'),mobileNav=document.querySelector('.mobile-nav');
menu?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('active');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});
mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.classList.remove('active');menu.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.category-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.category-tabs button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.catalog-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.querySelector(`#${btn.dataset.tab}`).classList.add('active')}));
document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('details').forEach(o=>o!==d&&o.removeAttribute('open'))}));
const types={Site:['Landing page','One page','Institucional','Portfólio','Hotsite','Blog','E-commerce','Portal'],Sistema:['MicroMVP','MVP','SaaS','ERP','CRM','Portal B2B'],Aplicativo:['App institucional','Agendamento','Delivery e pedidos','Marketplace','Equipe em campo','Área de membros','Outro aplicativo']};
const category=document.querySelector('#categoria'),type=document.querySelector('#tipo');
category.addEventListener('change',()=>{type.innerHTML='<option value="">Selecione o tipo</option>';(types[category.value]||[]).forEach(v=>type.add(new Option(v,v)));type.disabled=!category.value});
const form=document.querySelector('#projectForm'),steps=[...document.querySelectorAll('.form-step')],links=[...document.querySelectorAll('[data-step-link]')],prev=document.querySelector('#prevStep'),next=document.querySelector('#nextStep'),send=document.querySelector('#sendOrder'),bar=document.querySelector('#formProgress'),summary=document.querySelector('#summary');let current=0;
function validateStep(){const fields=[...steps[current].querySelectorAll('[required]')];for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}return true}
function values(){const data=new FormData(form),resources=data.getAll('recursos');return {nome:data.get('nome')||'',empresa:data.get('empresa')||'Não informado',email:data.get('email')||'',telefone:data.get('telefone')||'',local:data.get('local')||'Não informado',segmento:data.get('segmento')||'Não informado',categoria:data.get('categoria')||'',tipo:data.get('tipo')||'',objetivo:data.get('objetivo')||'',descricao:data.get('descricao')||'',prazo:data.get('prazo')||'',orcamento:data.get('orcamento')||'',recursos:resources.length?resources.join(', '):'Não informado',referencias:data.get('referencias')||'Não informado'} }
function buildSummary(){const d=values(),rows=[['Contato',`${d.nome} — ${d.telefone}`],['Empresa',d.empresa],['Projeto',`${d.categoria} — ${d.tipo}`],['Objetivo',d.objetivo],['Prazo',d.prazo],['Investimento',d.orcamento],['Recursos',d.recursos],['Ideia',d.descricao]];summary.innerHTML=rows.map(([a,b])=>`<div><span>${a}</span><b>${String(b).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</b></div>`).join('')}
function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));links.forEach((l,i)=>l.classList.toggle('active',i===current));prev.disabled=current===0;next.hidden=current===steps.length-1;send.hidden=current!==steps.length-1;bar.style.width=`${(current+1)/steps.length*100}%`;if(current===3)buildSummary();steps[current].scrollIntoView({behavior:'smooth',block:'start'})}
next.addEventListener('click',()=>{if(validateStep()&&current<3){current++;render()}});prev.addEventListener('click',()=>{if(current>0){current--;render()}});links.forEach((l,i)=>l.addEventListener('click',()=>{if(i<=current||validateStep()){current=i;render()}}));
form.addEventListener('submit',e=>{e.preventDefault();if(!validateStep())return;const d=values();const message=`Olá! Quero solicitar uma análise de projeto pela página da HoulffCode.\n\n*DADOS DO CONTATO*\nNome: ${d.nome}\nEmpresa: ${d.empresa}\nE-mail: ${d.email}\nTelefone: ${d.telefone}\nLocal: ${d.local}\nSegmento: ${d.segmento}\n\n*PROJETO*\nCategoria: ${d.categoria}\nTipo: ${d.tipo}\nObjetivo: ${d.objetivo}\nPrazo: ${d.prazo}\nFaixa de investimento: ${d.orcamento}\nRecursos: ${d.recursos}\n\n*DESCRIÇÃO*\n${d.descricao}\n\n*REFERÊNCIAS/OBSERVAÇÕES*\n${d.referencias}\n\nGostaria de conversar para definir o escopo e receber o orçamento final.`;window.open(`https://wa.me/5551996566717?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});
render();

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{
  if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}
}),{threshold:.12,rootMargin:'0px 0px -45px'});
const observeReveals=()=>document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>revealObserver.observe(el));
observeReveals();
document.querySelectorAll('.category-tabs button').forEach(button=>button.addEventListener('click',()=>requestAnimationFrame(observeReveals)));
